### ISSUE TITLE
Kill-reason textures not loading

### ISSUE THREAD

**Issue by slxdy** [mcolour/colourhud#1]
I think the image speaks for itself

![image](https://user-images.githubusercontent.com/61495410/191872818-9ad1d30d-502d-415b-8ad1-1d62589c3126.png)

I'm using Ubuntu 22 btw

**Comment by mcolour** [comment]
Well, I think I fixed it. Tested it on Ubuntu (obviously) by killing a bot with a scattergun, original and flame thrower. All killfeed icons appear just fine with no error textures in sight. Can't fully test this since I can only test Linux stuff on VirtualBox, where TF2 runs like crap and crashes for no reason whenever it wants.

**Comment by slxdy** [comment]
Works, can confirm
Thx!
